blank_issues_enabled: false
contact_links:
  - name: ‚ùì Ask a Question
    url: https://github.com/xacnio/kcik-tv-app/discussions
    about: If it's not a bug report or feature request, please use the Discussions section.
